### ISSUE TITLE
Invalid barcode

### ISSUE THREAD

**Issue by bkalish** [kenstir/hemlock#25]
I just installed the latest version of the CW MARS app from the Play Store. I was able to log in with my library card just fine, but when I go to Show Card I get the message "Invalid barcode: D7008XXXXX" (The number displays correctly, but I have obfuscated the last five digits here.) Below this, where I assume a simulated image of my library card should display, I instead see a graphic with yellow and black diagonal lines.

Either I am misunderstanding the purpose of the Show Card feature or I have encountered a bug.

**Comment by kenstir** [comment]
Hi Benjamin, you found a bug.  The CW MARS app you have is not rendering Code39 barcodes such as the one you have.  This is fixed in the latest version 4.0.3 which was just released to Beta.  Please sign up to be a Beta tester at https://play.google.com/apps/testing/org.cwmars and let me know if it is working for you.  Once you sign up and refresh the Play Store app you should see an update.  You can leave the Beta program at any time again through the Play Store app.

**Comment by kenstir** [comment]
p.s. thanks for the report!

**Comment by bkalish** [comment]
Yes, that fixed it! (I haven't yet had a chance to test scanning the barcode, but the error message is gone and a barcode is displayed.)

**Comment by kenstir** [comment]
Excellent, thanks for verifying!  I've promoted the Beta release to production so everyone will see the update.
